server:
  port: 8081
#savePath: /www/server/nginx-1.18.0/webapps/fileManager
savePath: /Users/xujiangtao/test
#savePath: C:/test
spring:
  thymeleaf:
    cache: false

fileUrl: http://xujiangtao.icu:81/fileManager
